plugins:
  halo-dev:
    plugins:
      - approve
      - assign
      - blunderbuss
      - cat
      - dog
      - help
      - heart
      - hold
      - label
      - lgtm
      - trigger
      - verify-owners
      - wip
      - yuks
      - retitle
      - lifecycle
      - milestone
      - milestonestatus
      - release-note
  metersphere:
    plugins:
      - approve
      - assign
      - blunderbuss
      - cat
      - dog
      - help
      - heart
      - hold
      - label
      - lgtm
      - trigger
      - verify-owners
      - wip
      - yuks
      - retitle
      - lifecycle
      - milestone
      - milestonestatus
  f2ccloud:
    plugins:
      - approve
      - assign
      - blunderbuss
      - cat
      - dog
      - help
      - heart
      - hold
      - label
      - lgtm
      - trigger
      - verify-owners
      - wip
      - yuks
      - retitle
      - lifecycle
      - milestone
      - milestonestatus
      - release-note      
  JohnNiang/action-test: # For test only
    plugins:
      - approve
      - assign
      - blunderbuss
      - cat
      - dog
      - help
      - heart
      - hold
      - label
      - lgtm
      - trigger
      - verify-owners
      - wip
      - yuks
      - retitle
      - lifecycle
  halo-dev/test-infra:
    plugins:
      - config-updater
config_updater:
  maps:
    # Update the config configmap whenever config.yaml changes
    config/prow/config.yaml:
      name: config
    # Update the plugin configmap whenever plugins.yaml changes
    config/prow/plugins.yaml:
      name: plugins
    config/prow/labels.yaml:
      name: label-config
    config/jobs/**/*.{yaml,yml}:
      name: job-config
      gzip: true

# Lower bounds in number of lines changed; XS is assumed to be zero.
size:
  s: 10
  m: 30
  l: 100
  xl: 500
  xxl: 1000

label:
  additional_labels:
    # These labels are used to make Tide merge with a non-default merge method
    - tide/merge-method-merge
    - tide/merge-method-rebase
    - tide/merge-method-squash

approve:
  - repos:
      - halo-dev
      - metersphere
      - f2ccloud
      - JohnNiang/action-test # Only for test
    require_self_approval: true

repo_milestone:
  # Default maintainer
  "":
    # You can curl the following endpoint in order to determine the github ID of your team
    # responsible for maintaining the milestones. You may need to specify the page number.
    # curl -H "Authorization: token <token>" "https://api.github.com/orgs/<org-name>/teams?page=N"
    maintainers_id: 5847331
    maintainers_team: milestone-maintainers
    maintainers_friendly_name: Milestone Maintainers Team

welcome:
  - repos:
      - halo-dev
      - JohnNiang # For test only
    message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> 🎉. Please refer to our [pull request process documentation](https://github.com/halo-dev/halo/blob/master/CONTRIBUTING.md) to help your PR have a smooth ride to approval. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://prow.halo.run/command-help). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). We want to make sure your contribution gets all the attention it needs! <br><br>Thank you, and welcome to Halo. :smiley:"

external_plugins:
  halo-dev:
    - name: cherrypicker
      events:
        - issue_comment
        - pull_request
    - name: needs-rebase
      events:
        - pull_request
  metersphere:
    - name: cherrypicker
      events:
        - issue_comment
        - pull_request
    - name: needs-rebase
      events:
        - pull_request        
